import Head from "next/head";
import styles from "../styles/Home.module.css";
import { ApolloClient, InMemoryCache, gql } from "@apollo/client";
import { ISpaceX, IHomeProps } from "../type";
import Launches from "../components/Launches";
import { GetStaticPropsContext } from "next";

export default function Home({ launches }: IHomeProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Space TS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>SpaceX Launches</h1>
        <div className={styles.grid}>
          {launches.map((launch) => (
            <Launches key={launch.id} launch={launch} />
          ))}
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps(context: GetStaticPropsContext) {
  const client = new ApolloClient({
    uri: "https://api.spacex.land/graphql/",
    cache: new InMemoryCache(),
  });

  const { data } = await client.query({
    query: gql`
      query GetLaunches {
        launchesPast(limit: 8) {
          id
          mission_name
          launch_date_local
          launch_site {
            site_name_long
          }
          links {
            article_link
            video_link
            mission_patch
          }
          rocket {
            rocket_name
          }
        }
      }
    `,
  });

  return {
    props: {
      launches: data.launchesPast,
    },
  };
}
